"""Add OTP fields to User model

Revision ID: 002_add_otp_fields
Revises: 9e8d7c6b5a4f
Create Date: 2026-01-28 11:55:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision = '002_add_otp_fields'
down_revision = '9e8d7c6b5a4f'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    columns = [col['name'] for col in inspector.get_columns('users')]

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        if 'otp_code' not in columns:
            batch_op.add_column(sa.Column('otp_code', sa.String(length=6), nullable=True))
        if 'otp_expiry' not in columns:
            batch_op.add_column(sa.Column('otp_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    columns = [col['name'] for col in inspector.get_columns('users')]

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        if 'otp_expiry' in columns:
            batch_op.drop_column('otp_expiry')
        if 'otp_code' in columns:
            batch_op.drop_column('otp_code')

    # ### end Alembic commands ###
