services:
  web:
    build: .
    image: giuliomastromartino/basketball-stats:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
      - PORT=8080
    volumes:
      # Sync current directory to /app so changes apply immediately (Fixes missing files)
      - .:/app
      # Keep instance persistent
      - ./instance:/app/instance
    restart: unless-stopped
