"""Add user role column

Revision ID: 9e8d7c6b5a4f
Revises: 4b2c3d4e5f6g
Create Date: 2026-01-28 10:18:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision = '9e8d7c6b5a4f'
down_revision = '4b2c3d4e5f6g'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    columns = [col['name'] for col in inspector.get_columns('users')]

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        if 'role' not in columns:
            batch_op.add_column(sa.Column('role', sa.String(length=20), server_default='editor', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    columns = [col['name'] for col in inspector.get_columns('users')]

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        if 'role' in columns:
            batch_op.drop_column('role')

    # ### end Alembic commands ###
